fos_rest:
  routing_loader:
    default_format: json
  view:
    formats:
      json: true
      xml: false
  exception:
    enabled: true
  body_listener:
    decoders:
      json: fos_rest.decoder.json
  format_listener:
    rules:
      - { path: '^/api', priorities: ['json'], fallback_format: json }